spring:
  application:
    name: dev
eureka:
  instance:
    prefer-ip-address: true  # Fix typo here
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
